RealEstates/RealEstates.Web/Models/ErrorViewModel.cs
using System;

namespace RealEstates.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RealEstates/RealEstates.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RealEstates.Services;
using RealEstates.Web.Models;

namespace RealEstates.Web.Controllers
{
    public class HomeController : Controller
    {
        private IDistrictService districtService;

        public HomeController(IDistrictService districtService)
        {
            this.districtService = districtService;
        }

        //Methodite v controllera vryshtat specialen type IActionResult, kojto e chast ot ASP.NET Core technologiqta:
        public IActionResult Index()
        {
            var districts = this.districtService.GetTopDistrictsByAveragePrice(1000);
            return View(districts); //vrystha View-to ot papka Views, koeto se namira v papka Home i ima ime Index.cshtml!
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RealEstates/RealEstates.Web/Controllers/RealEstatePropertiesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RealEstates.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RealEstates.Web.Controllers
{
    public class RealEstatePropertiesController : Controller
    {
        private IRealEstatePropertiesService realEstatePropertiesService;

        public RealEstatePropertiesController(IRealEstatePropertiesService realEstatePropertiesService)
        {
            this.realEstatePropertiesService = realEstatePropertiesService;
        }

        public IActionResult Search()
        {
            var realEstateProperties = this.realEstatePropertiesService.SearchByPrice(0, 100000);
            return this.View(realEstateProperties);
        }

        //[Authorize()] //usera trqbwa da se e lognal,za da vijda tazi stranica.
        //[Authorize(Roles = "Moderator")] //usera trqbwa da se e lognal kato Moderator,za da vijda tazi stranica.
        public IActionResult DoSearch(int minPrice, int maxPrice)
        {
            //if (!this.User.IsInRole("Admin"))
            //{
            //    return this.BadRequest(); //samo Admin user moje da vika tazi stranica!!!
            //}
            var realEstateProperties = this.realEstatePropertiesService.SearchByPrice(minPrice, maxPrice);
            return this.View(realEstateProperties);
        }
    }
}

RealEstates/RealEstates.Web/Views/Home/Index.cshtml
@using RealEstates.Services.Models;
@model IEnumerable<RealEstates.Services.Models.DistrictViewModel>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 @*class="display-4"*@>Welcome to Real Estates BG</h1>
</div>
<table class="table table-striped table-hover table-sm">
    <tr>
        <th>District</th>
        <th>RealEstate Properties Count</th>
        <th>Average Price</th>
        <th>Average Price Per m2</th>
        <th>Min Price</th>
        <th>Max Price</th>
    </tr>
    @foreach (DistrictViewModel district in this.Model.Where(x=>x.RealEstatePropertiesCount >= 20))
    { 
        <tr>
            <td>@district.Name</td>
            <td>@district.RealEstatePropertiesCount</td>
            <td>@district.AveragePrice €</td>
            <td>@district.AveragePricePerSquareMeter €/m²</td>
            <td>@district.MinPrice €</td>
            <td>@district.MaxPrice €</td>
        </tr>
    }
</table>
<div>
    <p>It is @DateTime.Now.DayOfWeek!!!</p>
</div>

RealEstates/RealEstates.Web/Views/RealEstateProperties/DoSearch.cshtml
@model IEnumerable<RealEstates.Services.Models.PropertyViewModel>
<h4>Search results:</h4>
<div>
    <table class="table table-striped table-hover table-sm table-bordered">
        <tr>
            <th>District</th>
            <th>Building Type</th>
            <th>Property Type</th>
            <th>Size, m²</th>
            <th>Year</th>
            <th>Price, €</th>
            <th>Floor</th>
        </tr>
        @foreach (var realEstateProperty in this.Model)
        {
            <tr>
                <td>@realEstateProperty.District</td>
                <td>@realEstateProperty.BuildingType</td>
                <td>@realEstateProperty.PropertyType</td>
                <td>@realEstateProperty.Size m²</td>
                <td>
                    @realEstateProperty.Year
                    @if (realEstateProperty.Year.HasValue)
                    {
                        @:г.
                    }
                </td>
                <td>@realEstateProperty.Price €</td>
                <td>
                    @if (realEstateProperty.Floor != "0  /0")
                    {
                        @realEstateProperty.Floor
                    }
                </td>
            </tr>
        }
    </table>
</div>

RealEstates/RealEstates.Web/Views/RealEstateProperties/Search.cshtml
<h4>Search properties by price</h4>
<form method="get" action="/RealEstateProperties/DoSearch"class="col-md-2"> @*formata shte izprashta dannite si vidim v addres bar-a, shtom e GET!*@
    <div>
        Min price: <input name="minPrice" class="form-control" />
    </div>
    <div>
        Max price: <input name="maxPrice" class="form-control" />
    </div>
    <hr/>
    <input type="submit" class="btn btn-primary float-right" value="Search"/>
</form>

RealEstates/RealEstates.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RealEstates.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/sb-admin-2.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RealEstates.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RealEstateProperties" asp-action="Search">Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - RealEstates.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>